clear;
clc;
close all;

%% FLHI SISO
Xt = -3:0.5:3;
Xv = -3:0.01:3;
FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_FLHI_SISO

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_FLHI_SISO

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_FLHI_SISO

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_FLHI_SISO

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_FLHI_SISO

%% FLHI SISO INVERSE
Xt = [0:0.1:10];
Xv = [0:0.01:10];
FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_FLHI_SISO_inverse

%% FLHI MISO
Xt = -3:1:3;
Xv = -3:0.1:3;
FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_FLHI_MISO

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_FLHI_MISO

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_FLHI_MISO

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_FLHI_MISO

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_FLHI_MISO

%% FLHI MIMO
Xt = 0:1:5;
Yt = 0:1:3;
Xv = 0:0.1:5;
Yv = 0:0.1:3;

FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_FLHI_MIMO

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_FLHI_MIMO

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_FLHI_MIMO

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_FLHI_MIMO

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_FLHI_MIMO

%% FLHI membership functions
Xo = [1 2 -2 -3;...
      2 5 -1 -2;...
      -4 -3 7 3;...
      -5 -4 3 2];

Xv = [1:0.05:(2-0.05)];

FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_FLHI_MF_SURF

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_FLHI_MF_SURF

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_FLHI_MF_SURF

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_FLHI_MF_SURF

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_FLHI_MF_SURF

Xv = [1:0.01:(2-0.01)];

FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_FLHI_MF_PLOT

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_FLHI_MF_PLOT

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_FLHI_MF_PLOT

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_FLHI_MF_PLOT

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_FLHI_MF_PLOT

%% DMC SISO
LIMIT_AXES = 0;
OUTPUT_YMAX = 0.1; OUTPUT_YMIN = -0.1;
CONTROL_YMAX = 0.2; CONTROL_YMIN = -0.2;
IGNORE_NONLINEARITY = 1;
FIGURE_NAME = 'IDEAL';
INTERPOLANT_TYPE = 0; % useless in this case
generate_DMC_SISO

IGNORE_NONLINEARITY = 0;
FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_DMC_SISO

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_DMC_SISO

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_DMC_SISO

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_DMC_SISO

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_DMC_SISO

%% DMC MISO UNCOUPLED
LIMIT_AXES = 1;
OUTPUT_YMAX = 60; OUTPUT_YMIN = -10;
CONTROL_YMAX = 30; CONTROL_YMIN = -10;
IGNORE_NONLINEARITY = 1;
FIGURE_NAME = 'IDEAL';
INTERPOLANT_TYPE = 0; % useless in this case
generate_DMC_MISO

IGNORE_NONLINEARITY = 0;
CONTROL_YMAX = 2; CONTROL_YMIN = -2;
FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_DMC_MISO

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_DMC_MISO

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_DMC_MISO

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_DMC_MISO

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_DMC_MISO

%% DMC MISO COUPLED
LIMIT_AXES = 1;
OUTPUT_YMAX = 60; OUTPUT_YMIN = -10;
CONTROL_YMAX = 30; CONTROL_YMIN = -10;
IGNORE_NONLINEARITY = 1;
FIGURE_NAME = 'IDEAL';
INTERPOLANT_TYPE = 0; % useless in this case
generate_DMC_MISO_coupled

IGNORE_NONLINEARITY = 0;
CONTROL_YMAX = 2; CONTROL_YMIN = -2;
FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_DMC_MISO_coupled

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_DMC_MISO_coupled

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_DMC_MISO_coupled

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_DMC_MISO_coupled

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_DMC_MISO_coupled

%% DMC MIMO
LIMIT_AXES = 1;
OUTPUT_YMAX = 20; OUTPUT_YMIN = 0;
CONTROL_YMAX = 5; CONTROL_YMIN = 0;
IGNORE_NONLINEARITY = 1;
FIGURE_NAME = 'IDEAL';
INTERPOLANT_TYPE = 0; % useless in this case
generate_DMC_MIMO

IGNORE_NONLINEARITY = 0;
CONTROL_YMAX = 2; CONTROL_YMIN = -0.5;
FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_DMC_MIMO

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_DMC_MIMO

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_DMC_MIMO

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_DMC_MIMO

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_DMC_MIMO

%% DMC SISO Robustness information
FIGURE_NAME = 'NEAREST'; INTERPOLANT_TYPE = 0;
generate_DMC_SISO_robustness

FIGURE_NAME = 'LINEAR'; INTERPOLANT_TYPE = 1;
generate_DMC_SISO_robustness

FIGURE_NAME = 'CUBIC'; INTERPOLANT_TYPE = 2;
generate_DMC_SISO_robustness

FIGURE_NAME = 'LANCZOS'; INTERPOLANT_TYPE = 3;
generate_DMC_SISO_robustness

FIGURE_NAME = 'SPLINE'; INTERPOLANT_TYPE = 4;
generate_DMC_SISO_robustness

%% Nonlinearity figures
FIGURE_NAME = 'NONLINEARITY_SISO';
generate_SISO_nonlinearity

FIGURE_NAME = 'NONLINEARITY_MISO_UNCOUPLED';
generate_MISO_nonlinearity_uncoupled

FIGURE_NAME = 'NONLINEARITY_MISO_COUPLED';
generate_MISO_nonlinearity_coupled

FIGURE_NAME = 'NONLINEARITY_MIMO';
generate_MIMO_nonlinearity